/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.ImageIcon;
import java.awt.*;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import jdk.jfr.SettingControl;


/**
 *
 * @author Aaron
 */
public class LoginView extends javax.swing.JFrame {

    
    /**
     * Creates new form LoginView
     */
    public LoginView() {
        initComponents();
        setSize(930,415);
        setResizable(false);
        
        
        setTitle("Ingresar al sistema");
        setLocationRelativeTo(null);
        this.repaint();
        
        //Colocamos una imagen de Icono
        Image icon = Toolkit.getDefaultToolkit().getImage("C:\\Users\\Orellana\\Desktop\\javaProject\\farmacia\\src\\images\\medicine_icon.png");
        setIconImage(icon);
         
       
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jblTitulo = new javax.swing.JLabel();
        jblUsuario = new javax.swing.JLabel();
        jblContraseña = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        jpdContraseña = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(22, 28, 130));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-350, -40, 820, 470));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 445, 418));

        jPanel2.setBackground(new java.awt.Color(18, 45, 61));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jblTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jblTitulo.setForeground(new java.awt.Color(0, 220, 208));
        jblTitulo.setText("INICIAR SESIÓN");
        jPanel2.add(jblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 50, 250, 60));

        jblUsuario.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        jblUsuario.setText("USUARIO: ");
        jPanel2.add(jblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 100, 30));

        jblContraseña.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jblContraseña.setForeground(new java.awt.Color(255, 255, 255));
        jblContraseña.setText("CONTRASEÑA:");
        jPanel2.add(jblContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(18, 45, 61));
        txtUsuario.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        txtUsuario.setForeground(new java.awt.Color(0, 220, 208));
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseExited(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel2.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 160, 20));

        jpdContraseña.setBackground(new java.awt.Color(18, 45, 61));
        jpdContraseña.setFont(new java.awt.Font("Calibri", 2, 14)); // NOI18N
        jpdContraseña.setForeground(new java.awt.Color(0, 220, 208));
        jpdContraseña.setBorder(null);
        jpdContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpdContraseñaActionPerformed(evt);
            }
        });
        jPanel2.add(jpdContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 190, 160, 30));

        btnIniciarSesion.setBackground(new java.awt.Color(0, 220, 208));
        btnIniciarSesion.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("INGRESAR");
        btnIniciarSesion.setBorder(null);
        btnIniciarSesion.setBorderPainted(false);
        btnIniciarSesion.setContentAreaFilled(false);
        btnIniciarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnIniciarSesion.setFocusable(false);
        btnIniciarSesion.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnIniciarSesion.setOpaque(true);
        btnIniciarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIniciarSesionMouseExited(evt);
            }
        });
        jPanel2.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 160, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 220, 208));
        jSeparator1.setForeground(new java.awt.Color(0, 220, 208));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, 160, 20));

        jSeparator2.setBackground(new java.awt.Color(0, 220, 208));
        jSeparator2.setForeground(new java.awt.Color(0, 220, 208));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 160, 160, 10));

        jButton1.setBackground(new java.awt.Color(18, 45, 61));
        jButton1.setForeground(new java.awt.Color(0, 220, 208));
        jButton1.setText("¿Perdiste tu contraseña?");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setFocusable(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 490, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void jpdContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpdContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpdContraseñaActionPerformed

    private void btnIniciarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseEntered
        
        btnIniciarSesion.setBackground(new Color(18, 40, 39));   
    }//GEN-LAST:event_btnIniciarSesionMouseEntered

    private void btnIniciarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseExited
        btnIniciarSesion.setBackground(new Color(0, 220, 208)); // BG default
    }//GEN-LAST:event_btnIniciarSesionMouseExited

    private void txtUsuarioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseEntered
        
    }//GEN-LAST:event_txtUsuarioMouseEntered

    private void txtUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseExited
        
    }//GEN-LAST:event_txtUsuarioMouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnIniciarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIniciarSesionMouseClicked
        
    }//GEN-LAST:event_btnIniciarSesionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jblContraseña;
    private javax.swing.JLabel jblTitulo;
    private javax.swing.JLabel jblUsuario;
    public javax.swing.JPasswordField jpdContraseña;
    public javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}


